name: Build & Tests
on: [push, pull_request]
jobs:
  qa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          # Use Node from .nvmrc if present, otherwise default to 20
          node-version-file: .nvmrc
          node-version: '20'
          cache: 'npm'
      - name: Install dependencies (ci if lockfile, else install)
        run: |
          if [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ]; then
            npm ci
          else
            echo "No lockfile found, using 'npm install' (temporary fallback)."
            npm install
          fi
      - run: npm run prettier:check
      - run: npm run lint:css
      - run: npm run lint:html
      - run: npm run lint:js
      - run: npm run test:a11y
      - run: npm run build