name: Format and Commit (one-off)

on:
  workflow_dispatch:

permissions:
  contents: write
  actions: read

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (with write permission)
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Use Node from .nvmrc
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Install dependencies (no lockfile fallback)
        run: |
          if [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Run Prettier (write)
        run: npm run format

      - name: Commit changes if any
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "chore(format): apply prettier"
            git push
          else
            echo "No changes to commit."
          fi