name: IndexNow Submit

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  submit-indexnow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Submit sitemap URLs to IndexNow
        run: node scripts/indexnow-submit.js